### ISSUE TITLE
NSFW images are not displayed in the user gallery

### ISSUE THREAD

**Issue by DavidAntonin** [sunnyark/civitai-shortcut#102]
NSFW images are not displayed in the user gallery regardless of the NSFW filter settings

**Comment by KatieWebb** [comment]
Have you figured anything out?
I assume it's an Civitai API change, but I don't know how to code.

**Comment by KatieWebb** [comment]
I think figured it out. When you change these, close and restart Automatic1111. I had to reload the UI a couple times after it restarted.

I edited the **civitai_gallery_action.py** in extensions\civitai-shortcut\scripts\civitai_manager_libs.
I changed all the instances of "show_nsfw=False" to show_nsfw=True. I did a find aand replace to change that.


I also Changed show_nsfw=False to show_nsfw=True

`def get_default_page_url(modelId, modelVersionId = None, show_nsfw=True, limit=0):
    
    if limit <= 0:
        limit = setting.usergallery_images_rows_per_page * setting.usergallery_images_column
    
    # 200이 최대값이다
    if limit > 200:
        limit = 200
        
    page_url = f"{civitai.Url_ImagePage()}?limit={limit}&modelId={modelId}"
    
    if modelVersionId:
        page_url = f"{page_url}&modelVersionId={modelVersionId}"
        
    if not show_nsfw:    
        page_url = f"{page_url}&nsfw=true"

    page_url = f"{page_url}&sort=Newest"
    
    return page_url`

I have a few images that are showing no preview. Not sure why.

**Comment by sunnyark** [comment]
I apologize for the delayed response. As announced, personal circumstances have caused significant delays. I are currently inquiring with civitai about this issue. The nsfw-related filtering in civitai’s image API is functioning differently than described. I will update you as soon as we have more information.
