### ISSUE TITLE
Error loading script: civitai_shortcut.py

### ISSUE THREAD

**Issue by thejohnd0e** [sunnyark/civitai-shortcut#14]
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\a\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Error loading script: civitai_shortcut.py
Traceback (most recent call last):
  File "C:\a\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\a\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\a\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_shortcut.py", line 11, in <module>
    from scripts.civitai_manager_libs import classification_action
  File "C:\a\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\classification_action.py", line 9, in <module>
    from . import sc_browser
  File "C:\a\stable-diffusion-webui\extensions\civitai-shortcut\scripts\civitai_manager_libs\sc_browser.py", line 34, in <module>
    def on_sc_classification_list_select(evt: gr.SelectData,sc_types, sc_search, show_only_downloaded_sc):
AttributeError: module 'gradio' has no attribute 'SelectData'

**Comment by sunnyark** [comment]
It seems that there is a version mismatch with Gradio. It appears that an update to SDUI is required.

**Comment by thejohnd0e** [comment]
> It seems that there is a version mismatch with Gradio. It appears that an update to SDUI is required.

should i update gradio: 3.16.2? if yes, how i can?

**Comment by sunnyark** [comment]
The version displayed at the bottom of sdui should be higher. Please check the version at the bottom of sdui.
![screenshot 2023-04-20 150341](https://user-images.githubusercontent.com/40237431/236674446-61c86bfd-ca2d-466a-853c-02987d518f46.png)

**Comment by thejohnd0e** [comment]
> The version displayed at the bottom of sdui should be higher. Please check the version at the bottom of sdui. ![screenshot 2023-04-20 150341](https://user-images.githubusercontent.com/40237431/236674446-61c86bfd-ca2d-466a-853c-02987d518f46.png)

![image](https://user-images.githubusercontent.com/115493464/236674636-878cb11b-aaab-49b4-a399-ef2768fef6c3.png)

now i have:

**Comment by sunnyark** [comment]
Gradio version 3.23 or higher is required, which means you need to update SDUI. However, there may be other conflicts due to significant changes in SDUI. We recommend installing SDUI in a new location and testing it.

**Comment by thejohnd0e** [comment]
> Gradio version 3.23 or higher is required, which means you need to update SDUI. However, there may be other conflicts due to significant changes in SDUI. We recommend installing SDUI in a new location and testing it.

I reinstalled SD and now everythink works, thank you!
