### ISSUE TITLE
Is it possible to prompt to the front-end page after the download ends

### ISSUE THREAD

**Issue by av8dtop** [sunnyark/civitai-shortcut#30]
Is it possible to prompt to the front-end page after the download ends

**Comment by sunnyark** [comment]
@av8dtop I couldn't find that method. It seems like Gradio doesn't allow for such an approach.

**Comment by av8dtop** [comment]
> @av8dtop I couldn't find that method. It seems like Gradio doesn't allow for such an approach.

So it is, thanks for the reply
