### ISSUE TITLE
Sort order in shortcut browse mode

### ISSUE THREAD

**Issue by Pemmican6** [sunnyark/civitai-shortcut#35]
When I use the browse function, the sort order of the models displayed seems to be random/unknown to me.
Is there any way to determine a specific sort order, or at least have it sort by name?

Thank you.

**Comment by sunnyark** [comment]
@Pemmican6 It has been incorporated to be sorted based on the current model's name. We will try to add more features in the future. Thank you.

**Comment by Pemmican6** [comment]
Thanks, appreciate the response
