### ISSUE TITLE
Civitai Shortcut: No Civitai Internet Shortcut file, use blank

### ISSUE THREAD

**Issue by Dreadfxl** [sunnyark/civitai-shortcut#5]
Hello,

I'm constantly having "Civitai Shortcut: No Civitai Internet Shortcut file, use blank" on the console.
Can't see any models or do anything really

**Comment by sunnyark** [comment]
Initially, it is normal to see that message upon installation. Once you have added one or more items (shortcuts), the message should disappear. Does it continue to appear even after adding items or does it not allow you to add them?

**Comment by sunnyark** [comment]
I will modify the wording of the guidance message.

**Comment by Dreadfxl** [comment]
> Initially, it is normal to see that message upon installation. Once you have added one or more items (shortcuts), the message should disappear. Does it continue to appear even after adding items or does it not allow you to add them?

It doesn't allow me to add any. 
Every drop-down list are empty.

Thank you!

**Comment by sunnyark** [comment]
![image](https://user-images.githubusercontent.com/40237431/233270998-1aecddae-70fd-45b9-b272-1c686affa05c.png)
Are only messages like the ones shown in the image appearing in the console window and are shortcuts not being registered? Can we see the contents of the CivitaiShortCut.json file located in the extensions\civitai-shortcut folder? This file is where shortcuts are saved. If this file is empty, it means that there is a program error or that it is not a valid Civitai model shortcut.

![image](https://user-images.githubusercontent.com/40237431/233272351-6ec8cc92-151a-490c-85e3-7b88b55e950c.png)
Also, what is the version of stable diffusion? This extension program was developed based on Gradio 3.23.0 commit: 22bcc7be.

**Comment by Dreadfxl** [comment]
![image](https://user-images.githubusercontent.com/32430923/233487857-a2e6d718-e82b-4934-9014-f9e15193a2d6.png)

Well I don't even have that CivitaiShortCut.json file. Shouldn't it be created when I installed the extension?

![image](https://user-images.githubusercontent.com/32430923/233488696-03b76cd5-b706-4134-9a8a-d11c33865c8d.png)

I think I'm fine?

Thank you

**Comment by Dreadfxl** [comment]
Just reinstalled the extension and this is my .json file

![image](https://user-images.githubusercontent.com/32430923/233490048-af6f9b54-6d6d-451a-a420-8f40e87b01d1.png)

**Comment by sunnyark** [comment]
The commit for 'stable diffusion' is different (22bcc7be). To avoid potential issues with other extensions, it may be better to download 'stable diffusion' in a new folder and test it out separately. What do you think about trying this?

**Comment by sunnyark** [comment]
how you added the shortcut?
1. browser to browser or 
![browsertobrowser](https://user-images.githubusercontent.com/40237431/233503357-52885805-ceda-484e-923b-6b2a8998f49b.gif)

2. file to browser
![filetobrowser](https://user-images.githubusercontent.com/40237431/233503378-740199bb-8c89-4f3f-8da4-bc5c9dd1e80e.gif)

**Comment by Dreadfxl** [comment]
> how you added the shortcut?
> 
> 1. browser to browser or
>    ![browsertobrowser](https://user-images.githubusercontent.com/40237431/233503357-52885805-ceda-484e-923b-6b2a8998f49b.gif)
>          
>            [
>              
>            
>                ![browsertobrowser](https://user-images.githubusercontent.com/40237431/233503357-52885805-ceda-484e-923b-6b2a8998f49b.gif)
>              ](https://user-images.githubusercontent.com/40237431/233503357-52885805-ceda-484e-923b-6b2a8998f49b.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/40237431/233503357-52885805-ceda-484e-923b-6b2a8998f49b.gif)
> 2. file to browser
>    ![filetobrowser](https://user-images.githubusercontent.com/40237431/233503378-740199bb-8c89-4f3f-8da4-bc5c9dd1e80e.gif)
>          
>            [
>              
>            
>                ![filetobrowser](https://user-images.githubusercontent.com/40237431/233503378-740199bb-8c89-4f3f-8da4-bc5c9dd1e80e.gif)
>              ](https://user-images.githubusercontent.com/40237431/233503378-740199bb-8c89-4f3f-8da4-bc5c9dd1e80e.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/40237431/233503378-740199bb-8c89-4f3f-8da4-bc5c9dd1e80e.gif)

Thank you for showing me how to do it!

I've reinstalled everything, and added the shortcut like you showed and it works now!

Thank you very much!

**Comment by BanditSan** [comment]
> 

Why all this complicated way instead of simple text input with submit button?

Option 1 do not work in linux. Tryed both Firefox and Chromium browsers.
Even tryed editing your code:
```civitai_internet_url = gr.File(label="Civitai Internet Shortcut", file_count="multiple", file_types=[".url", ".desktop"])```

Still did not worked after adding ".desktop" to file types. But this might be because drag&drop browser 2 browser might not be using ".desktop" format.

Option 2 works with .desktop files but thats kinda stupid way of doing it since you need first create that file to upload it to extension.
For reference how file looks:
```$ cat ChilloutMix\ -\ Chilloutmix-Ni-pruned-fp32-fix\ \|\ Stable\ Diffusion\ Checkpoint\ \|\ Civitai.desktop 
[Desktop Entry]
Version=1.0
Type=Link
Name=ChilloutMix - Chilloutmix-Ni-pruned-fp32-fix | Stable Diffusion Checkpoint | Civitai
Comment=
Icon=user-bookmarks
URL=https://civitai.com/models/6424/chilloutmix?modelVersionId=11745
```

My suggestion just replace or add as alternative simple text input field where you can copy-paste url

**Comment by sunnyark** [comment]
When I first developed it, there was a text field, but for some reasons, it was changed to its current state.
The target area was too small for drag-drop and it was also difficult to handle multiple inputs, which is why I made the changes.
I also use both Edge and Chrome browsers, and since there were no issues, I'm not sure why you are experiencing this problem.
anyway, I plan to add a way to input text through a text field.

**Comment by sunnyark** [comment]
I have added a text input box. Please test to see if it is working as expected.

**Comment by BanditSan** [comment]
> When I first developed it, there was a text field, but for some reasons, it was changed to its current state.
The target area was too small for drag-drop and it was also difficult to handle multiple inputs, which is why I made the changes.

Thats makes more sence why it was implemented like this.

> I also use both Edge and Chrome browsers, and since there were no issues, I'm not sure why you are experiencing this problem.

Issue is that im on linux and most likely browsers on linux handle url drag&drop a bit different. My guess is that on windows it always creates .url file browser 2 browser or browser 2 desktop. On linux it might just do silent url copy on one window and does `Paste and Go` on other. But when you drag&drop to something like desktop it creates `.desktop` file which is native linux shortcut file

**Comment by BanditSan** [comment]
> I have added a text input box. Please test to see if it is working as expected.

Looks to be working with minor bug.
If you use "main" url for model works fine.
E.g. this url works [https://civitai.com/models/21813/edge-of-realism](https://civitai.com/models/21813/edge-of-realism)

But if you click on different versions
![image](https://user-images.githubusercontent.com/6743235/235552135-b72bc6f7-96d8-48f1-b3a4-b9fb12a32f63.png)
You get url like this [https://civitai.com/models/21813?modelVersionId=51913](https://civitai.com/models/21813?modelVersionId=51913)
I guess url parser gets confused which number is models ID :)

**Comment by sunnyark** [comment]
Your guess is correct. I didn't think of that. I will make the correction soon. Thank you.

> > I have added a text input box. Please test to see if it is working as expected.
> 
> Looks to be working with minor bug. If you use "main" url for model works fine. E.g. this url works https://civitai.com/models/21813/edge-of-realism
> 
> But if you click on different versions ![image](https://user-images.githubusercontent.com/6743235/235552135-b72bc6f7-96d8-48f1-b3a4-b9fb12a32f63.png) You get url like this https://civitai.com/models/21813?modelVersionId=51913 I guess url parser gets confused which number is models ID :)
