### ISSUE TITLE
'cp932' codec can't decode byte 0xe0 in position 3: illegal multibyte sequence

### ISSUE THREAD

**Issue by ARLeader** [sunnyark/civitai-shortcut#7]
Hi I am receiving the following errors when I tried to drop either URL from Chrome or a URL Shortcut file on the desktop

![image](https://user-images.githubusercontent.com/2335997/233391272-257111d4-5dfd-4939-859e-eeffcf0da399.png)

From what I have been googled, cp932 (JP) is a JP encoding in which my machine is operating on. This seems like the app is using the machine's language as the default encoding

![image](https://user-images.githubusercontent.com/2335997/233391504-952f0344-5804-408a-829c-1fcded6ab0cc.png)

**Comment by sunnyark** [comment]
Can you upload the shortcut file? I think there may be a character encoding issue, and I would like to test it.

**Comment by sunnyark** [comment]
Alternatively, in the "civitai-shortcut\scripts\civitai_manager_libs\util.py" file, there is a section defined as "def load_InternetShortcut(path) -> str:". Please add encoding as follows, and try again after restarting.

def load_InternetShortcut(path)->str:
    urls = ""
    try:    
        with open(path, 'r', encoding='utf8') as f:
            InternetShortcut = f.readline()
            if not InternetShortcut or not "[InternetShortcut]" in InternetShortcut:
                return
            InternetShortcut = f.readline()
            if not InternetShortcut:
                return
            urls = InternetShortcut[4:]
    except Exception as e:
        printD(e)
        return

    return urls.strip()

**Comment by sunnyark** [comment]
or notepad -> save as -> encoding->utf-8  ?

**Comment by ARLeader** [comment]
> Alternatively, in the "civitai-shortcut\scripts\civitai_manager_libs\util.py" file, there is a section defined as "def load_InternetShortcut(path) -> str:". Please add encoding as follows, and try again after restarting.
> 
> def load_InternetShortcut(path)->str: urls = "" try: with open(path, 'r', encoding='utf8') as f: InternetShortcut = f.readline() if not InternetShortcut or not "[InternetShortcut]" in InternetShortcut: return InternetShortcut = f.readline() if not InternetShortcut: return urls = InternetShortcut[4:] except Exception as e: printD(e) return
> 
> ```
> return urls.strip()
> ```

After adding encoding to the open function. Dragging the Desktop's Internet shortcut is working now. 
But when trying to drag link in browser is giving this instead

 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
![image](https://user-images.githubusercontent.com/2335997/233423289-5e89b55e-4ebd-4793-803c-be8723ea11d5.png)

**Comment by ARLeader** [comment]
I may misunderstand the usage instruction, There are several test scenario with different result 

1) Saving shortcut (.url) by saving the URL from chrome bookmark, Then drag the shortcut to the extension > OK
2) Saving shortcut (.url) by dragging the address bar to desktop, Then drag the shortcut to the extension > OK

So it seems like reading from a desktop shortcut is ok for now, but I am not sure if the scenarios below are meant for the extension or not.

3) Click and hold CivitAI's model image and switch to the extension tab > Got the 'utf-8' error
![image](https://user-images.githubusercontent.com/2335997/233429731-d0878ff5-fac1-4e3c-8ba8-568908f6bb45.png)

4) Click and hold the address bar (Like No.2), then to the extension tab > Nothing 
![image](https://user-images.githubusercontent.com/2335997/233430689-84750173-bb99-4b9f-8ce5-05960fefb3d0.png)

**Comment by sunnyark** [comment]
![Animation](https://user-images.githubusercontent.com/40237431/233436215-db1f2529-2311-43e9-996b-724f94e0804c.gif)

internet address  drag -->  drop

**Comment by sunnyark** [comment]
![Animation](https://user-images.githubusercontent.com/40237431/233439430-57331b02-88f1-4bff-80f3-a4fdf5962b61.gif)
1. internet address drag(hold)  --> drop(release) to desktop
2. internet shortcut(.url) drag(hold) --> drop(release) stable diffusion
