### ISSUE TITLE
Feature Request: additional button to select/deselect all items of 'Scanned Model List' when scanning models for Civitai

### ISSUE THREAD

**Issue by fsilveiradev** [sunnyark/civitai-shortcut#78]
When using [Assistance>Scan and Update Models>Scan Models] for calculating hashes and searching the model in Civitai, if the user has many non-registered models, the list of scanned models might be very long. In this case, if the user doesn't want to re-scan every model of this long list, the user must manually uncheck every item of the list, which is very inconvenient.

Suggestion: add buttom for checking/unchecking all items from Scanned Model List.

This way, if the user has many models, but only want to search Civitai for only a few of them, it is easier to uncheck the entire list and manually check the few items the user wants to search for.

**Comment by sunnyark** [comment]
Understood. I will take it into consideration.

**Comment by fsilveiradev** [comment]
Thanks for the inclusion!
