### ISSUE TITLE
Wrong folder location for Wildcards

### ISSUE THREAD

**Issue by fsilveiradev** [sunnyark/civitai-shortcut#8]
The current folder location for downloaded wildcards is set as:
"stable-diffusion-webui\extensions\stable-diffusion-webui-wildcards\Wildcards"

However, for quite a while the [Wildcards extension is obsolete](https://github.com/jtkelm2/stable-diffusion-webui-1) and the default extension handling wildcards now is the [Dynamic Prompts extension](https://github.com/adieyal/sd-dynamic-prompts).

The new folder location for wildcards should be:
"stable-diffusion-webui\extensions\sd-dynamic-prompts\wildcards"

or for organized collections:
"stable-diffusion-webui\extensions\sd-dynamic-prompts\collections"

**Comment by sunnyark** [comment]
Thank you. I will proceed with changing the location.

**Comment by sunnyark** [comment]
I have made changes to allow for setting specific download folders.
You can configure this in the manage -> settings.

**Comment by fsilveiradev** [comment]
Works great! Thanks for the changes! This extension is so useful it should be an official extension.
May I mention another suggestion?

When downloading a model, even if you uncheck "Create individual folders with" it creates a subfolder inside the models folder, together with all sample images and trigger words. Currently the extra networks UI always display extra buttons for each subfolder above the cards, and it can get very cluttered. Also, these sample images and trigger words .txt file is duplicated, since the extension already saves it in the sc_infos folder.

When scanning already downloaded models in the manager tab, there is an option to "Create individual model version folder" and "Create a model folder corresponding to the model type". If both are unchecked the model information is downloaded directly in the models folder, and the additional samples and .txt files are only saved in the sc_infos folder.

Would it be possible to add this same option when downloading the model directly through the browsing tab?

**Comment by sunnyark** [comment]
The current selection option allows creating separate folders for each version of the model, and if unchecked, only the base folder for the model will be created. Are you asking to add an option to enable downloading to the type-based base folder (e.g. models/lora) when downloading the model directly through the browsing tab?

**Comment by sunnyark** [comment]
The trigger file and images are remnants of a previous version. I kept them because I thought I might need them someday, but since they're unnecessary, I'll get rid of them.

**Comment by fsilveiradev** [comment]
Exactly!
This way you can keep every model file in the same base folder.

**Comment by sunnyark** [comment]
For those who wish to use folders freely, there is an "open folder" function available, and it is okay to move files to the base folder if desired. I recommend this option. 
However, downloading files directly to the base folder may cause errors due to duplicate file names and it may be difficult to manage files directly. I will explore better options. 
Thank you.
